//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFBloodBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonorDetail
    {

        public int DonorID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Gender { get; set; }
        public string Ethnicity { get; set; }
        public string BloodType { get; set; }
        public string RHFactor { get; set; }
        public string MedicalHistory { get; set; }
        public int NhsID { get; set; }
    
        public virtual tableUser tableUser { get; set; }
    }
}
